(function(g){var l=window.AmazonUIPageJS||window.P,m=l._namespace||l.attributeErrors,r=m?m("CustomerReviewsCommonAssets",""):l;r.guardFatal?r.guardFatal(g)(r,window):r.execute(function(){g(r,window)})})(function(g,l,m){function r(){}g.when("A","cr-log-utils","cr-streaming-utils").register("cr-ajax-model",function(c,d,b){function a(a){n[a]&&(n[a].abort(),delete n[a])}function f(k,e,p,q,t,u,g,m){e=e||{};e.params=e.params||{};var r;r=u?u:w=w++;u=r;t=t?t:e.error||function(){};q=q?q:0;p=p?p:2;m=m?m:"FATAL";
var y="FATAL"===m?0:1,v=e.finallyCallback||function(){};g||(g="reviewsAjax"+h++,l.uet&&l.uet("tc",g));e.params.scope=g;e.contentType=e.contentType||"application/x-www-form-urlencoded;charset\x3dUTF-8";var x=e.success||function(){};e.success=function(a){delete n[u];"function"===typeof x&&x(a);"function"===typeof v&&v(a)};e.error=function(b,h,c){a(u);b=b||{};var n=(b.http||{}).status||"[]";q++;q<p?(h="AJAX Post to "+k+" from "+l.location.href+" failed, status code passed through parameter was: "+h+
", status code extracted from XHR HTTP object was: "+n+", attempt "+q+" of "+p+", error message was: \n "+c,d.logError(h,"WARN"),f(k,e,p,q,t,u,g,m)):(h="AJAX Post to "+k+" from "+l.location.href+" failed, status code passed through parameter was: "+h+", status code extracted from XHR HTTP object was: "+n+", exhausted "+p+" attempt(s), error message was: \n "+c,d.logError(h,m),d.logCount("AjaxFailureFatal",y),"function"===typeof t&&t(b),"function"===typeof v&&v(b))};"function"!==typeof e.chunk&&(e.chunk=
function(a){"appendFadeIn"===a[0]?b.appendFadeIn(a):"replace"===a[0]&&b.replace(a)});n[u]=c.post(k,e);return u}var h=0,w=1,n={};return{abort:a,post:f,postWithoutFatals:function(a,b,h,c,t,n,d){return f(a,b,h,c,t,n,d,"WARN")}}});"use strict";g.when("A","cr-jQuery","cr-log-utils","cr-number-utils").register("cr-A",function(c,d,b,a){c.getListFromState=function(a){var b=c.map(d("#cr-state-object, .cr-state-object"),function(a){return d(a).data("state")});return c.reduce(b,function(b,c){c!==m&&c[a]!==m&&
b.push(c[a]);return b},[])};c.getValueFromState=function(a){var f=c.getListFromState(a);1<f.length&&b.logError("More than one  value defined for key: "+a,"ERROR");return f[0]};var f={top:-100,left:-100};c.inView=function(a){a=a||d();if("function"===typeof a.offset){var b=(a.offset()||f).top-d(l).scrollTop();a=0<=b;b=b<d(l).height();return a&&b}return!1};c.onScreenAndVisible=function(b,c){b=b||d();c=a.isFiniteNumber(c)?c:0;if(b instanceof d||b.jquery){if(!b.is(":visible"))return!1;b=b[0].getBoundingClientRect();
return b.top>=0-c&&b.left>=0-c&&b.bottom<=d(l).height()+c&&b.right<=d(l).width()+c}return!1};c.compositeEventWrapper=function(a,f,d){var k=a;d&&(k=c.throttle(k,d,{trailing:!1}));return b.jsGuard(function(a){a&&(k(a),f&&a.$event&&a.$event.preventDefault())})};c.freeze=function(a){return"undefined"!==typeof Object&&"function"===typeof Object.freeze?Object.freeze(a):a};c.isFrozen=function(a){return"undefined"!==typeof Object&&"function"===typeof Object.isFrozen?Object.isFrozen(a):!1};return c});"use strict";
g.when("jQuery").register("cr-jQuery",function(c){return c});"use strict";g.declare("reviews-constants",{PUSH_STATE:!0,REPLACE_STATE:!1,RATING_SERVICE_CONTEXT_ID:"ReviewsConsumption",data:{REFTAG:"data-reftag",CSM_COUNTER:"data-csm-counter",getReviews:{STANDARD:"data-reviews-state-param",CHECKED:"data-reviews-param-checked",UNCHECKED:"data-reviews-param-unchecked"}},events:{CONTENT_CHANGED:"reviews:content-changed",RELOAD:"reviews:content-reload",RELOAD_COMPLETE:"reviews:content-reload-complete",
AUTOSCROLL_COMPLETE:"reviews:autoscroll-complete",FILTER_FIRE_AGGREGATE:"reviews:filter-action:aggregate:trigger",FILTER_FIRE_UPDATE:"reviews:filter-action:trigger",FILTER_AGGREGATE:"reviews:filter-action:aggregate",FILTER_PUSH:"reviews:filter-action:push-state",FILTER_REPLACE:"reviews:filter-action:replace-state",PAGINATION:"reviews:page-action",SEARCH_TEXTBOX:"reviews:search-textbox",SEARCH_BUTTON:"reviews:search-button",VOTE:"reviews:vote-action",TOGGLE_CLASS_CLICK:"reviews:toggle-class:click",
AJAX_POST:"reviews:ajax-post",SCROLL_TO_ELEMENT_CLICK:"reviews:scroll-to-element:click",OPEN_MASH_MODAL:"reviews:open-mash-modal",FILTER_APPLY:"reviews:filter-action:apply",FILTER_CHANGE:"reviews:filter-action:change",FILTER_TAB_CLICKED:"reviews:filter-action:tab-clicked",FILTER_APPLY_BEGIN:"reviews:filter-action:apply-begin",FILTER_APPLY_SUCCESS:"reviews:filter-action:apply-success",FILTER_APPLY_ERROR:"reviews:filter-action:apply-error",FILTER_APPLY_DONE:"reviews:filter-action:apply-done",INPUT_COMMENT:"reviews:input-comment",
SUBMIT_COMMENT:"reviews:submit-comment",OPEN_SUBMISSION_COMMENT:"reviews:open-comment-submission",SORT_COMMENTS:"reviews:sort-comments",MORE_COMMENTS:"reviews:more-comments",EDIT_COMMENT:"reviews:edit-comment",CANCEL_EDIT_COMMENT:"reviews:cancel-edit-comment",DELETE_COMMENT:"reviews:delete-comment",SUBMIT_EDIT_COMMENT:"reviews:submit-edit-comment",MODIFY_EDIT_COMMENT:"reviews:modify-edit-comment",INPUT_PRODUCT_LINK:"reviews:input-product-link",SELECT_PRODUCT_LINK:"reviews:select-product-link",STAR_RATING_CLICK:"ryp:star-rating-click",
STAR_RATING_CLEAR:"ryp:star-rating-clear-click"},filterOptions:{SORT_KEY:"sortBy",HELPFUL:"helpful",RECENT:"recent",LEGACY_HELPFUL:"byRankDescending",LEGACY_RECENT:"bySubmissionDateDescending",MOBILE_HELPFUL:"sh",MOBILE_RECENT:"sd",STAR_KEY:"filterByStar",ALL_STARS:"all_stars",ONE_STAR:"one_star",TWO_STAR:"two_star",THREE_STAR:"three_star",FOUR_STAR:"four_star",FIVE_STAR:"five_star",POSTIVE:"positive",CRITICAL:"critical",FORMAT_KEY:"formatType",ALL_FORMATS:"all_formats",CURRENT_FORMAT:"current_format",
AVP_KEY:"reviewerType",ALL_REVIEWS:"all_reviews",AVP_ONLY:"avp_only_reviews",MEDIA_KEY:"mediaType",ALL_CONTENTS:"all_contents",MEDIA_ONLY:"media_reviews_only",LANGUAGE_KEY:"filterByLanguage",HEIGHT_KEY:"filterByHeight",WEIGHT_KEY:"filterByWeight"},keycodes:{ENTER:13,BACK_SPACE:8,SPACE:32},aui:{HIDDEN:"aok-hidden",NOWRAP:"aok-nowrap"}});"use strict";g.when("A","cr-string-utils","cr-log-utils").register("cr-popup",function(c,d,b){function a(a){var h={};a&&a.data&&(h=a.data);var g=d.defaultIfBlank(h.url,
a.$target.find("a").andSelf().filter("a").attr("href")),n=d.defaultIfBlank(h.title,"CustomerReviews"),n=""+n,k="";c.each({width:"500",height:"500",resizable:"1",scrollbars:"1",toolbar:"0",status:"1"},function(a,b){a=d.defaultIfBlank(h[b],a);k+=b+"\x3d"+a+","});var k=k.slice(0,-1),e=null;try{(e=l.open(g,n,k))?e.focus():b.logError("Unable to move focus to popup window with data: "+d.stringify(h),"ERROR"),a.$event.preventDefault()}catch(p){b.logError("Unable to open window with parameters: "+d.stringify(h),
"FATAL",p)}return e}c.declarative("cr-popup",["click"],b.jsGuard(a));return{popup:a}});"use strict";g.when("A","cr-jQuery","reviews-constants","cr-ajax-model","cr-string-utils","cr-global-view").register("cr-generic-declarative-actions",function(c,d,b,a,f,h){function g(a){e(a)&&a.data.selector&&a.data.cssClass&&(d(a.data.selector).toggleClass(a.data.cssClass),a.$event.preventDefault(),c.trigger("a:pageUpdate"))}function n(a){e(a)&&a.data.scrollToSelector&&(h.scrollTo(a.data.scrollToSelector,0),a.$event.preventDefault())}
function k(b){if(e(b)&&b.data.url&&b.data.params){b.$event.preventDefault();c.declarative.remove(b.$currentTarget,q.AJAX_POST);b=b.data;var f=b.params,n=d(b.indicatorSelector)[0],h=p(d.fn.hide,b.hideOnSuccessSelector),k=p(d.fn.show,b.showOnFailureSelector);d(b.removeOnLoadSelector).remove();a.post(b.url,{params:f,indicator:n,success:h,error:k})}}function e(a){return a&&a.data&&a.$event&&"function"===typeof a.$event.preventDefault}function p(a,b){if(b&&"function"===typeof a)return function(){var c=
d(b);0<c.length&&a.call(c)}}var q=b.events;c.declarative(q.TOGGLE_CLASS_CLICK,"click",g);c.declarative(q.SCROLL_TO_ELEMENT_CLICK,"click",n);c.declarative(q.AJAX_POST,"click",k);return{toggleCssClass:g,scrollToElement:n,ajaxPost:k}});"use strict";g.register("cr-global-model",function(){return{generateUrl:function(c,d){c&&"/"!==c.charAt(c.length-1)&&(c+="/");c&&d&&(c=c+"ref\x3d"+d);return c}}});"use strict";g.when("A","a-expander","cr-jQuery","reviews-constants","cr-string-utils").register("cr-global-view",
function(c,d,b,a,f){function h(a){var b="";if(a&&a.closest!==m){var c=a.closest("*["+e.REFTAG+"]");c&&(b=c.attr(e.REFTAG))}f.isBlank(b)&&a&&a.closest!==m&&(a=a.closest("*[rel]"))&&(b=a.attr("rel"));return f.defaultIfBlank(b,"cm_cr_unknown")}function g(a){return a&&"function"===typeof a.is?a.is("*["+e.getReviews.CHECKED+"]")&&a.is("*["+e.getReviews.UNCHECKED+"]"):!1}function n(a){return a&&a.has!==m&&a.is!==m?0<a.find(":checked").length||a.is(":checked"):!1}function k(a,b){return a&&a.attr!==m&&b?
f.parseJSON(a.attr(b))||{}:{}}var e=a.data;c.on("a:pageUpdate",function(){d!==m&&d.initializeExpanders()});return{getReviewsStateParamsFromElement:function(a){var b=c.reduce(e.getReviews,function(a,b){return a+"*["+b+"],"},"").slice(0,-1),f;b&&a&&a.closest!==m&&(f=a.closest(b));return g(f)?n(f)?k(f,e.getReviews.CHECKED):k(f,e.getReviews.UNCHECKED):k(f,e.getReviews.STANDARD)},getReftag:function(a){var c;a&&a.$target&&(c=a.$target);a&&a.id&&(c=b("#"+a.id));a&&a.expander&&a.expander.$expander&&(c=a.expander.$expander);
c=h(c);"cm_cr_unknown"===c&&a&&a.data&&a.data.reftag&&(c=a.data.reftag);return c},getReftagByDom:h,scrollTo:function(a,c){a=b(a).offset();c=c||0;var f=b("#cr-state-object").data("state"),f=f!==m&&f.disableScroll;a&&a.top!==m&&!f&&(b("html,body").stop(),b("html,body").animate({scrollTop:a.top-c},{queue:!1,duration:500}))}}});"use strict";g.when("cr-A","cr-jQuery","cr-lazy-widget-model","cr-lazy-widget-view","cr-log-utils","cr-number-utils","cr-string-utils","cr-uri-utils","ready").register("cr-lazy-widget-controller",
function(c,d,b,a,f,h,g,n){function k(d){var e=c.getValueFromState("lazyWidgetDomainWhitelist"),h=n.getCurrentHostname();if(e)b:{for(var k=0;k<e.length;k++)if(g.endsWith(h,e[k])){f.logCount("LazyWidgetInvalidDomain",0);break b}f.logError("AJAX triggered from invalid domain: "+h,"WARN");f.logCount("LazyWidgetInvalidDomain",1)}else f.logCount("LazyWidgetInvalidDomain",1),f.logError("AJAX triggered with null whitelist from domain: "+h,"WARN");b.loadLazyWidgets(a.getLazyWidgetStubs())&&(f.logCount("LazyWidgetTrigger",
1),f.logCount("LazyWidgetTrigger:"+d,1))}var e={};e.bufferPixels=h.convertToInteger(c.getValueFromState("lazyWidgetLoaderBufferPixels"),1E3);e.delayBeforeTriggering=h.convertToInteger(c.getValueFromState("lazyWidgetLoaderDelayBeforeTriggering"),5E3);e.triggerLazyLoadIfWidgetWithinBuffer=function(f){b.lazyLoadHasTriggered()||a.getLazyWidgetStubs().each(function(a,b){if(c.onScreen(d(b),e.bufferPixels))return k("scroll"),c.off("scroll",e.triggerLazyLoadIfWidgetWithinBuffer),!1})};var l={};e.logVisibleStubMetrics=
function(b){a.getLazyWidgetStubs().each(function(a,b){a=d(b);b=a.data("widget-name");!l[b]&&c.onScreen(a)&&(f.logCount("VisibleLazyWidgetStub",1),f.logCount("VisibleLazyWidgetStub:"+b,1),l[b]=!0)})};c.on("scroll",e.logVisibleStubMetrics);c.on("scroll",e.triggerLazyLoadIfWidgetWithinBuffer);d(a.getHoverTargets()).mouseenter(function(){k("hover")});f.logCount("LazyWidgetTrigger",0);return c.freeze(e)});"use strict";g.when("cr-A","cr-ajax-model","cr-uri-utils","ready").register("cr-lazy-widget-model",
function(c,d,b){var a={},f=c.getValueFromState("lazyWidgetLoaderUrl"),h=!1;a.loadLazyWidgets=function(a){if(!h&&0<a.length){h=!0;var n=c.getValueFromState("asin"),k=c.getValueFromState("lazyWidgetCsrfToken"),e=c.getValueFromState("languageOfPreference");a=c.reduce(a,function(a,b){return a+"\x26lazyWidget\x3d"+c.$(b).data("widget-name")},f+"?asin\x3d"+n+"\x26csrf\x3d"+k+"\x26language\x3d"+e);d.postWithoutFatals(a,{success:r,cache:!1,headers:{"cache-control":"no-cache"},params:b.getUrlParametersMap()||
{}});return!0}return!1};a.lazyLoadHasTriggered=function(){return h};return c.freeze(a)});"use strict";g.when("cr-A","cr-jQuery","ready").register("cr-lazy-widget-view",function(c,d){var b={},a=c.getValueFromState("lazyWidgetLoaderHoverTargetsSelector")||"";b.getLazyWidgetStubs=function(){return d(".cr-lazy-widget")};b.getHoverTargets=function(){d(a)};return c.freeze(b)});"use strict";g.when("A").register("cr-log-utils",function(c){function d(a,b,c){l.ueLogError&&("string"!==typeof b&&(b="FATAL"),
c?l.ueLogError(c,{message:a,logLevel:b.toUpperCase(),attribution:"CustomerReviewsJS"}):l.ueLogError({message:a},{logLevel:b.toUpperCase(),attribution:"CustomerReviewsJS"}))}function b(a,b){return"string"===typeof b?b+a:"CustomerReviews:"+a}return{logError:d,jsGuard:function(a){if("function"===typeof a)return function(){try{return a.apply(this,arguments)}catch(b){d("Uncaught Error in function","FATAL",b)}};d("Unable to wrap non-function","ERROR");return a},incrementCount:function(a,c){l.ue&&(a=b(a,
c),c=l.ue.count(a)||0,l.ue.count(a,c+1))},logCount:function(a,c,d){l.ue&&(a=b(a,d),l.ue.count(a,c))}}});"use strict";g.when("A","reviews-constants").register("cr-mash-utils",function(c,d){var b=!1;g.when("mash").execute(function(){b=!0});return{isMash:function(){return b}}});"use strict";g.when("A","cr-log-utils").register("cr-number-utils",function(c,d){return{convertToInteger:function(b,a){if(b===parseInt(b,10))return b;if(null!==b&&b!==m&&""!==b)return parseInt(b.replace(/[^0-9]/g,""),10);if(a!==
m)return a;d.logError("convertToInteger","Cannot convert "+b+" to Integer");return 0},isFiniteNumber:function(b){return"number"===typeof b&&!isNaN(b)&&isFinite(b)}}});"use strict";g.when("A","cr-jQuery").register("cr-streaming-utils",function(c,d){return{appendFadeIn:function(b){if(null!==b&&2<b.length&&null!==b[1]&&null!==b[2]){var a=b[1];b=d(b[2]).hide();d(a).append(b);c.fadeIn(b,500,"ease-in-out",function(){})}},replace:function(b){if(null!==b&&2<b.length&&null!==b[1]&&null!==b[2]){var a=b[2];
d(b[1]).replaceWith(d(a))}}}});"use strict";g.when("A","cr-log-utils").register("cr-string-utils",function(c,d){function b(a){return null===a||a===m?!0:0===c.trim(a).length}return{defaultIfBlank:function(a,c){return b(a)?c:a},isBlank:b,parseJSON:function(a){try{return c.parseJSON(a)}catch(b){d.logError("Unable to parse JSON object","ERROR",b)}return null},startsWith:function(a,b){return a===b?!0:null===a||null===b?!1:0===a.indexOf(b)},endsWith:function(a,b){if(a===b)return!0;if(null===a||null===b)return!1;
var c=a.lastIndexOf(b);return-1!==c&&c===a.length-b.length},stringify:function(a){return l.JSON&&l.JSON.stringify?l.JSON.stringify(a):a}}});"use strict";g.when("A").register("cr-uri-utils",function(c){function d(){return l.location.hostname}function b(a){a=a||l.location.href;var b={},d=a.indexOf("?"),g=a.indexOf("#");a=a.slice(d+1,g>d?g:m)||"";d=[];-1<a.indexOf("\x26")?d=a.split("\x26"):-1<a.indexOf("\x3d")&&(d=[a]);c.each(d,function(a,c){0<a.indexOf("\x3d")&&(a=a.split("\x3d"),b[a[0]]=a[1])});return b}
return{getUrlParametersMap:b,addKeyValuePair:function(a,c,d){d=d||0;if(b(a)[c]===d||!a||!c)return a;c="?"+c+"\x3d"+d;return-1<a.indexOf("?")?a.replace("?",c+"\x26"):a+c},getCurrentHostname:d,getDomainRealmBaseUrl:function(a){a=a||d();if(-1!==a.indexOf(".corp.amazon.com"))return"https://development.amazon.com/";if(-1!==a.indexOf(".proxy.amazon.com")){a=a.split(".")[1];var b={dub:"https://pre-prod.amazon.co.uk/",pdx:"https://pre-prod.amazon.co.jp/",pek:"https://pre-prod.amazon.cn/"};return b[a]!==m?
b[a]:"https://pre-prod.amazon.com/"}return"/"}}});"use strict";g.when("A","cr-uri-utils","cr-string-utils","3p-urijs","cr-jQuery").register("cr-extended-uri-utils",function(c,d,b,a,f){function g(){return a(l.location.href)}function m(){return g().query()}return f.extend(d,{getCurrentUri:g,getCurrentQueryString:m,getCurrentQueryParameters:function(){return a.parseQuery(m())},isAmazonDomain:function(c){if("string"===typeof c||c instanceof String)c=a(c);var d=b.startsWith(c.domain(),"amazon");!1===d&&
(c=c.hostname(),c=c.substring(c.indexOf(".")+1),d=b.startsWith(c,"amazon"));return d},setQueryParameters:function(d,f){if("string"===typeof d||d instanceof String)d=a(d);c.each(f,function(a,c){b.isBlank(a)?d.removeSearch(c):d=d.setSearch(c,a)});return d},setReftag:function(c,d){if("string"===typeof c||c instanceof String)c=a(c);for(var e=c.segment(),f=!1,g=e.length-1;0<=g;g--)if(b.startsWith(e[g],"ref\x3d")){f=!0;e[g]="ref\x3d"+d;break}f||e.push("ref\x3d"+d);c.segment(e);return c}})});"use strict";
g.when("A","cr-jQuery").register("histogram-trigger",function(c,d){function b(){c.onScreen(d("#histogramTable"))&&c.trigger("scroll")}c.on.afterLoad(b);return{triggerHistogram:b}})});
/* ******** */
(function(b){var e=window.AmazonUIPageJS||window.P,f=e._namespace||e.attributeErrors,a=f?f("CustomerReviewsMedleyAssets",""):e;a.guardFatal?a.guardFatal(b)(a,window):a.execute(function(){b(a,window)})})(function(b,e,f){b.when("A","medley-twister-view","medley-twister-model","ready").register("medley-twister-controller",function(a,c,g){function b(a){a=g.getASIN();var d=c.getDisplayedASIN();d&&a!==d&&(c.fadeReviews(!0),g.getReviews(d,function(){g.setASIN(d)},function(){},function(){c.fadeReviews(!1)}))}
var e=c.getLoadedASIN();g.setASIN(e);a.on("a:pageUpdate",b);return{onTwist:b}});"use strict";b.when("A","cr-jQuery").register("medley-twister-view",function(a,c){return{getDisplayedASIN:function(){return String(c("#ASIN").val()||"")},getLoadedASIN:function(){return(c("#cr-state-object").data("state")||{}).asin||""},fadeReviews:function(a){!1===a?c("#cm-cr-review-list .review,#most-recent-reviews-content .review").css("opacity",1):c("#cm-cr-review-list .review,#most-recent-reviews-content .review").css("opacity",
.5)}}});"use strict";b.when("A","cr-global-model","cr-ajax-model","cr-uri-utils","cr-jQuery").register("medley-twister-model",function(a,c,b,e,f){function h(a){var b=e.getUrlParametersMap()||{};b.asin=a;return b}var d;return{setASIN:function(a){d=a||""},getASIN:function(){return d},getReviews:function(a,c,e,d){var k=f("#cr-state-object").data("state");"string"===typeof a&&10===a.length?b.post(k.medleyReviewsAjaxUrl,{params:h(a),attribution:"getMedleyReviews",success:c,error:e,finallyCallback:d}):
"function"===typeof d&&d()}}})});
/* ******** */
(function(h){var l=window.AmazonUIPageJS||window.P,n=l._namespace||l.attributeErrors,a=n?n("CustomerReviewsVotingAssets"):l;a.guardFatal?a.guardFatal(h)(a,window):a.execute(function(){h(a,window)})})(function(h,l,n){h.when("A","vote-model","vote-view","a-modal").register("vote-controller",function(a,b,g,e){function d(a,b){h(a,b);g.showElementByCssSelector(a,b.inFlight)}function h(a,b){g.hideElementByCssSelector(a,b.hideVoteComponents);b.hideAbuseComponents&&g.hideElementByCssSelector(a,b.hideAbuseComponents)}
function c(c,l){l.isReportAbuse&&(c=a.$("#mobile-abuse-"+l.voteInstanceId),e.get(c).hide());d(c,l.cssSelectors);b.submitVote(l.ajaxUrl,l.voteValue,l.voteInstanceId,l.csrfT,l.voteDimension,function(a){if(!0===a){a=c;var b=l.cssSelectors;h(a,b);g.showElementByCssSelector(a,b.onSuccess)}else a=c,b=l.cssSelectors,h(a,b),g.showElementByCssSelector(a,b.onError)},function(){var a=c,b=l.cssSelectors;h(a,b);g.showElementByCssSelector(a,b.onError)})}a.declarative("reviews:vote-action","click",function(a){c(a.$target,
a.data);a.$event.preventDefault()});return{submitVote:c}});h.when("A","cr-ajax-model").register("vote-model",function(a,b){return{submitVote:function(a,e,d,h,c,f,l){b.post(a,{params:{voteInstanceId:d,voteValue:e,csrfT:h,voteDimension:c},attribution:"submitVote",success:f,error:l})}}});h.when("A").register("vote-view",function(a){function b(a,b){return a.closest(".cr-vote").find(b)}return{hideThankYouAlert:function(a){b(a,".cr-vote-success").addClass("aok-hidden")},showThankYouAlert:function(a){b(a,
".cr-vote-success").removeClass("aok-hidden")},showErrorAlert:function(a){b(a,".cr-vote-error").removeClass("aok-hidden")},showFeedback:function(a){b(a,".cr-vote-feedback").removeClass("aok-hidden")},hideFeedback:function(a){b(a,".cr-vote-feedback").addClass("aok-hidden")},hideButtons:function(a){b(a,".cr-vote-buttons").addClass("aok-hidden")},hideElementByCssSelector:function(a,e){b(a,e).addClass("aok-hidden")},showElementByCssSelector:function(a,e){b(a,e).removeClass("aok-hidden")}}})});
/* ******** */
(function(h){var l=window.AmazonUIPageJS||window.P,n=l._namespace||l.attributeErrors,a=n?n("CustomerReviewsGalleryAssets"):l;a.guardFatal?a.guardFatal(h)(a,window):a.execute(function(){h(a,window)})})(function(h,l,n){h.when("A","load").register("review-image-asset-loader",function(a){var b=!1;a.ajax("/gp/customer-reviews/aj/private/reviewsGallery/get-image-gallery-assets",{method:"post",success:function(a){h.load.css(a.reviewsLightboxCSS);var e=document.createElement("script");e.type="text/javascript";
e.async=!0;e.setAttribute("crossorigin","anonymous");e.src=a.reviewsLightboxJS;document.getElementsByTagName("head")[0].appendChild(e);b=!0;h.register("review-image-assets-loaded",{})},error:function(){var a;a="/gp/customer-reviews/aj/metrics/log-values?noCache="+(new Date).getTime();a+="&SimpleStack:ReviewImageAssetLoaderFailure=1";l.Image&&((new Image).src=a)}});return{isLoaded:function(){return b}}});h.when("A","cr-jQuery","cr-log-utils","reviews-constants","review-image-assets-loaded").register("review-image-binder",
function(a,b,g,e){function d(a,c,f,d,e){if(!(a&&c&&f instanceof b&&d instanceof b&&e instanceof b))return g.logError("Invalid parameters for imageBinder.initializeEventHandlers with ASIN: "+a+", galleryName: "+c+", $popoverTrigger: "+f+", $thumbnails: "+d+", $galleryLink: "+e,"FATAL"),!1;var l="reviewsLightbox-ready-"+c;d.click(function(){k(a,c);var e=d.index(this);f.click();h.when(l).execute(function(){b("#"+c).trigger("jumpToImageAtIndex",e)})});e.click(function(){k(a,c);f.click();h.when(l).execute(function(){b("#"+
c).trigger("hideImmersiveView")})});return!0}function k(a,b){if(!a||!b)return g.logError("Invalid parameters for imageBinder.initializeImageGallery with ASIN: "+a+", galleryName: "+b,"FATAL"),!1;if(c)return!0;(new ReviewsLightbox(b,"DESKTOP")).initializeForAsin(a);return c=!0}var c=!1,f={};h.when("reviewsLightbox-js").execute(function(){var a=b("#reviews-image-gallery-container"),c=a.attr("data-asin");0<a.length&&c&&d(c,"reviews-image-gallery",a.find(".a-popover-trigger"),a.find(".review-image-tile"),
a.find(".reviews-image-gallery-link"))});a.on(e.events.RELOAD_COMPLETE,function(){f={}});return{bindReview:function(a,c,d){var e=new ReviewGallery(d,"DESKTOP"),g=b("#"+c);g.find(".review-image-tile").each(function(c){b(this).click(function(){f[a]||(e.initializeForReview(a),f[a]=!0);g.find(".a-popover-trigger").click();h.when("reviewsLightbox-ready-"+d).execute(function(){e.render();e.showImageAtIndex(c)})})})},initializeImageGallery:k,initializeEventHandlers:d}});h.when("A","cr-jQuery",
"cr-video-model","cr-video-view","reviews-constants").register("cr-video-controller",function(a,b,g,e,d){function k(){a.each(b(".review-views .review"),function(a){a&&a.id&&(a=g.getEmbedInfo(a.id))&&(g.isAiryLoaded()||g.loadAssets(),e.embedVideo(a))})}a.on(d.events.RELOAD_COMPLETE,function(){k()});k();return{initAll:k}});h.when("cr-jQuery").register("cr-video-model",function(a){var b=!1;return{getEmbedInfo:function(b){var e="video-block-"+b,d=a("#"+b+" .video-url").val(),k=a("#"+b+" .video-slate-img-url").val(),
c=a("#cr-video-swf-url").val();return b&&d&&c?{videoDomId:e,videoUrl:d,videoSlateImgUrl:k,videoSwfUrl:c}:!1},isAiryLoaded:function(){return b},loadAssets:function(){var g=a("#cr-airy-js-source-url").val(),e=a("#cr-airy-css-source-url").val();"string"===typeof g&&"string"===typeof e&&(h.load.js(g),h.load.css(e));b=!0}}});h.when("cr-jQuery","afterLoad").register("cr-video-view",function(a){return{embedVideo:function(a){h.when("Airy").execute(function(g){g.embed({parentId:a.videoDomId,streamingUrls:[a.videoUrl],
slateImages:{preloadSlate:a.videoSlateImgUrl},swfUrl:a.videoSwfUrl,desiredMode:"html"})})}}})});
/* ******** */
(function(g){var m=window.AmazonUIPageJS||window.P,p=m._namespace||m.attributeErrors,e=p?p("CustomerReviewsFilteringAssets",""):m;e.guardFatal?e.guardFatal(g)(e,window):e.execute(function(){g(e,window)})})(function(g,m,p){g.when("cr-A","cr-jQuery","cr-filtering-view","cr-filtering-model","cr-global-view","reviews-constants","cr-streaming-utils").register("cr-filtering-controller",function(e,f,b,d,l,c,k){function h(n){var a=!1,c=!1;n.toggleFilters&&(c=!0);d.setASIN(b.getLoadedFilterParam("asin"));
a=d.setReviewerType(n.reviewerType,c)||a;a=d.setFormatType(n.formatType,c)||a;a=d.setFilterByKeyword(n.filterByKeyword,c)||a;a=d.setFilterByLanguage(n.filterByLanguage,c)||a;a=d.setSortOrder(n.sortOrder,c)||a;a=d.setStarFilter(n.filterByStar,c)||a;a=d.setPageNumber(n.pageNumber,c)||a;a=d.setHeightFilter(n.filterByHeight,c)||a;return a=d.setWeightFilter(n.filterByWeight,c)||a}function q(a){if(h(a.data)||a.data.forceReload)a.data.sortOrder&&b.setSortDropdown(a.data.sortOrder),b.hideReviewLoadError(),
b.hideReviews(),b.showLoadingSpinner(),e.trigger(c.events.FILTER_APPLY_BEGIN,a),d.getReviews(function(){b.showReviews();"filterByHeight"===d.getActiveTab()&&b.scrollToFilterIndex("filterByHeight");"filterByWeight"===d.getActiveTab()&&b.scrollToFilterIndex("filterByWeight");e.trigger(c.events.FILTER_APPLY_SUCCESS,a)},function(){b.showReviewLoadError();e.trigger(c.events.FILTER_APPLY_ERROR,a)},function(){b.hideLoadingSpinner();e.trigger(c.events.FILTER_APPLY_DONE,a);e.trigger(c.events.RELOAD_COMPLETE)},
function(a){"appendFadeIn"===a[0]?k.appendFadeIn(a):"replace"===a[0]&&k.replace(a)},l.getReftag(a)),a.data.scrollToSelector&&l.scrollTo(a.data.scrollToSelector,0)}function g(a){a&&a.data&&q(a)}function a(a){a&&a.data&&a.$target&&a.data.filterType&&(a.data[a.data.filterType]=a.$target.val(),q(a))}function r(a){a&&a.data&&a.data.filterType&&(b.deactivateFilterTabHeaders(),b.activateFilterTabHeader(a.data.filterType),b.changeFilterOptionsTo(a.data.filterType),d.setActiveTab(a.data.filterType),"filterByHeight"!==
a.data.filterType&&"filterByWeight"!==a.data.filterType||b.scrollToFilterIndex(a.data.filterType))}d.setReviewsAjaxUrl(b.getReviewsAjaxUrl());b.enableDesktopDPFilterDropdown();e.declarative(c.events.FILTER_APPLY,"click",e.compositeEventWrapper(g,!0,100));e.declarative(c.events.FILTER_CHANGE,"change",e.compositeEventWrapper(a,!0,100));e.declarative(c.events.FILTER_TAB_CLICKED,"click",r);d.setReviewerType(b.getLoadedFilterParam("reviewerType"),!1);d.setFormatType(b.getLoadedFilterParam("formatType"),
!1);d.setFilterByKeyword(b.getLoadedFilterParam("filterByKeyword"),!1);d.setFilterByLanguage(b.getLoadedFilterParam("filterByLanguage"),!1);d.setStarFilter(b.getLoadedFilterParam("filterByStar"),!1);d.setSortOrder(b.getLoadedFilterParam("sortOrder"),!1);d.setPageNumber(b.getLoadedFilterParam("pageNumber"),!1);d.setHeightFilter(b.getLoadedFilterParam("filterByHeight"),!1);d.setWeightFilter(b.getLoadedFilterParam("filterByWeight"),!1);d.setLanguage(b.getLoadedFilterParam("languageOfPreference"));b.getLoadedFilterParam("showLanguageFilter")?
d.setActiveTab("filterByLanguage"):b.getLoadedFilterParam("showHeightFilter")&&(d.setActiveTab("filterByHeight"),b.scrollToFilterIndex("filterByHeight"));return{setFilterParams:h,onFilterApply:g,onFilterChange:a,onFilterTabClicked:r}});"use strict";g.when("A","cr-ajax-model","ready").register("cr-filtering-model",function(e,f){function b(){return h.asin||""}function d(){return g||""}function l(a,c){c?h[a]=c:delete h[a]}function c(a,c,b){var d=!1;a&&c!==p&&(d=k(a)!==c,!d&&b&&(c="CLEAR_VALUE",d=!0),
l(a,c));return d}function k(a){return h[a]||""}var h={},g="",m;return{getReviews:function(a,c,b,d,l){var e=g;m&&f.abort(m);l&&(e+="ref\x3d"+l);m=f.post(e,{params:h,attribution:"getFilteredReviews",success:a,error:c,finallyCallback:function(){b();m=0},chunk:d})},setASIN:function(a){var c=b()!==a;l("asin",a);return c},getASIN:b,setReviewsAjaxUrl:function(a){var c=d()!==a;g=a||"";return c},getReviewsAjaxUrl:d,setReviewerType:function(a,b){return c("reviewerType",a,b)},getReviewerType:function(){return k("reviewerType")},
setFormatType:function(a,b){return c("formatType",a,b)},getFormatType:function(){return k("formatType")},setFilterByKeyword:function(a,b){return c("filterByKeyword",a,b)},getFilterByKeyword:function(){return k("filterByKeyword")},setFilterByLanguage:function(a,b){return c("filterByLanguage",a,b)},getFilterByLanguage:function(){return k("filterByLanguage")},setSortOrder:function(a,b){return c("sortBy",a,b)},getSortOrder:function(){return k("sortBy")},setStarFilter:function(a,b){return c("filterByStar",
a,b)},getStarFilter:function(){return k("filterByStar")},setPageNumber:function(a,b){return c("pageNumber",a,b)},getPageNumber:function(){return k("pageNumber")},setHeightFilter:function(a,b){return c("filterByHeight",a,b)},getHeightFilter:function(){return k("filterByHeight")},setWeightFilter:function(a,b){return c("filterByWeight",a,b)},getWeightFilter:function(){return k("filterByWeight")},getFilterParams:function(){return h||{}},updateFilterParam:l,setActiveTab:function(a){return l("activeTab",
a)},getActiveTab:function(){return k("activeTab")},setLanguage:function(a){return l("language",a)}}});"use strict";g.when("cr-A","cr-jQuery","a-dropdown","ready").register("cr-filtering-view",function(e,f,b){function d(b){return(f("#cr-state-object").data("state")||{})[b]||""}return{getReviewsAjaxUrl:function(){return(f("#cr-state-object").data("state")||{}).reviewsAjaxUrl||""},showLoadingSpinner:function(){var b=e.getValueFromState("onLoadShowHideElements");f(b).removeClass("aok-hidden")},hideLoadingSpinner:function(){var b=
e.getValueFromState("onLoadShowHideElements");f(b).addClass("aok-hidden")},hideReviews:function(){f(".filterable-reviews-content").addClass("aok-hidden")},showReviews:function(){f(".filterable-reviews-content").removeClass("aok-hidden")},showReviewLoadError:function(){f(".review-load-error").removeClass("aok-hidden")},hideReviewLoadError:function(){f(".review-load-error").addClass("aok-hidden")},deactivateFilterTabHeaders:function(){f(".cr-tab-header-text").removeClass("cr-tab-active")},activateFilterTabHeader:function(b){f(".cr-tab-header-text-"+
b).addClass("cr-tab-active")},changeFilterOptionsTo:function(b){f(".cr-tab-content").addClass("aok-hidden");f(".cr-tab-content-"+b).removeClass("aok-hidden")},getLoadedFilterParam:d,setSortDropdown:function(d){b.getSelect("cm-cr-sort-dropdown").setValue(d)},scrollToFilterIndex:function(b){var c;c=0;var e;e=d("isCardTreatmentEnabled")?f(".cr-horizontal-scroll-list-cardify-padding ul \x3e *:first-child"):f(".cr-horizontal-scroll-list-padding ul \x3e *:first-child");var h=f(m).width();b=f("ul#"+b+"-button-list")[0];
if(e===p||h===p||b===p)c=-1;else{var g=parseInt(b.dataset.index);e=parseInt(e.css("padding-left").replace("px",""));if(-1!==g){c=e-h/2;for(h=0;h<g;h++)c+=f("#"+b.children[h].firstElementChild.id).outerWidth(!0);c+=f("#"+b.children[g].firstElementChild.id).outerWidth(!0)/2}}0>c||f(".cr-filter-scroll-container").animate({scrollLeft:c},50)},enableDesktopDPFilterDropdown:function(){f("#cm-cr-dp-review-sort-type").removeClass("aok-hidden")}}});"use strict";g.when("cr-A","cr-lighthut-terms-view","reviews-constants",
"cr-log-utils").register("cr-lighthut-terms-controller",function(e,f,b,d){function g(b){b&&b.filterByKeyword!==p&&(f.setSelected(b.filterByKeyword),d.incrementCount("LighthutTermClicked"))}e.on(b.events.FILTER_APPLY_BEGIN,e.compositeEventWrapper(function(b){b&&b.data&&g(b.data)}));return{onFilterApplied:g}});"use strict";g.when("A","cr-jQuery","ready").register("cr-lighthut-terms-view",function(e,f){return{setSelected:function(b){b=b.replace(/ /g,"_");var d=(b=f("#cr-lighthouse-term-"+b))&&b.hasClass("cr-lighthut-term-selected");
f(".cr-lighthut-term-selected").removeClass("cr-lighthut-term-selected");d||b.addClass("cr-lighthut-term-selected")}}})});
/* ******** */
